name: Create AnyCloud Release

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    # - name: Install AnyCloud
    #   run: npm install -g anycloud

    # Development only
    - name: Install Anycloud
      run: |
        curl -fOL https://github.com/alantech/alan/releases/download/v0.1.42-beta19/anycloud-ubuntu.tar.gz
        tar -xzf anycloud-ubuntu.tar.gz

    - name: Deploy
      env:
        CREDENTIALS_NAME: ${{ secrets.CREDENTIALS_NAME }}
        CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET: ${{ secrets.AWS_SECRET }}
        GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
      run: |
        ALAN_TECH_ENV=staging ./anycloud new -n -c single-aws -a ci-deploy
